---
name: Lint Code Base

defaults:
  run:
    shell: bash

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      # Checkout the code base
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # Install node (for npm) and use it to install eslint and stylelint dependencies.
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm ci

      # Run Linter against code base
      - name: Super-Linter
        uses: github/super-linter@v4.9.5

        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.js
          CSS_FILE_NAME: .stylelintrc.js
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          FILTER_REGEX_EXCLUDE: (.*/we_b_wor_k3.yml|.*.csv)

  perltidy:
    name: Run perltidy on Perl Files
    runs-on: ubuntu-latest
    container:
      image: perl:5.32
    steps:
      - uses: actions/checkout@v3
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: cpanm -n Perl::Tidy@20220613
      - name: perltidy --version
        run: perltidy --version
      - name: Run perltidy
        shell: bash
        run: |
          shopt -s extglob globstar nullglob
          perltidy --pro=./.perltidyrc -b -bext='/' ./**/*.p[lm] ./**/*.t && git diff --exit-code
