---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

defaults:
  run:
    shell: bash

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to main
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # Install node (for npm) and use it to install eslint and stylelint dependencies.
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm ci

      ################################
      # Run Linter against code base #
      ################################
      - name: Super-Linter
        uses: github/super-linter@v4.5.1

        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.js
          CSS_FILE_NAME: .stylelintrc.js
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_JAVASCRIPT_STANDARD: false

      # This doesn't work and so is disabled.
      # This either should be in a separate workflow or the workflow shoule be renamed.
      ##################
      # Run Perl tests #
      ##################
      #- name: Run Perl Tests
      #  uses: skx/github-action-tester@master
      #  with:
      #    script: .github/run-perl-tests.sh
