---
###########################
## Linter GitHub Actions ##
###########################
name: Lint Code Base

defaults:
  run:
    shell: bash

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to main
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  lint:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # Install node (for npm) and use it to install eslint and stylelint dependencies.
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm ci

      ################################
      # Run Linter against code base #
      ################################
      - name: Super-Linter
        uses: github/super-linter@v4.8.1

        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.js
          CSS_FILE_NAME: .stylelintrc.js
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          FILTER_REGEX_EXCLUDE: (.*/we_b_wor_k3.yml|.*.csv)

  perltidy:
    name: Run perltidy on Perl Files
    runs-on: ubuntu-latest
    container:
      image: perl:5.32
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: cpanm -n Perl::Tidy@20220613
      - name: perltidy --version
        run: perltidy --version
      - name: Run perltidy
        shell: bash
        run: |
          shopt -s extglob globstar nullglob
          perltidy --pro=./.perltidyrc -b -bext='/' ./**/*.p[lm] ./**/*.t && git diff --exit-code
